### PR TITLE
chore(monitoring): delete monitoring package

### PR DESCRIPTION
**Pull request by IzumiSy**
# Background

`tailor-platform/monitoring` package should be deprecated and moved its content onto our documents.

# Changes

* Delete the package.
* Add `.gitattributes` as supplement.

### CODE REVIEW

**Review by toiroakr — APPROVED** [review]
削除か非推奨したほうがいいですかね？
https://www.npmjs.com/package/@tailor-platform/monitoring/access

**Review by murayama-r — APPROVED** [review]
LGTM

**Comment by murayama-r** [comment]
@toiroakr さんのコメントの対応はマージ後で問題なさそうなのでマージします。

**Comment by IzumiSy** [comment]
Deprecated
image

**Pull request merged**
